spring:
  main:
    banner-mode: off

  datasource:
    url:
    username:
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
app:
  description: Dev version of credit service
  version: 0.0.1-SNAPSHOT
  server:
    stage: dev