server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank_app
    username: user
    password: user

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

app:
  server:
    url: ${app.server.url}









