spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/bank_app
    username: user
    password: user

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
app:
  description: Dev version of bank_app
  version: 0.0.1-SNAPSHOT
  server:
    stage: dev





